### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by ZixiaChen** [cobblesteve01/Eaglercraft-Extras#14]
Hi cobblesteve long time no see and eagler 1.9 is released it has elytra’s too! If u can I add it that would be amazing and also add a 1.9 mobile version thx.

**Comment by ZixiaChen** [comment]
Oh also real 1.12 is also out I have the repo cloned hurry before get dmca’ed

**Comment by bahabryra** [comment]
What is the link

**Comment by ZixiaChen** [comment]
Eaglercraft lamba/1.9
http://git.zelz.net/Eagler-lambda/hoosiertransfer-mod/releases

**Comment by ZixiaChen** [comment]
1.12
https://github.com/ZixiaChen/Eaglercraft-1.12

**Comment by cobblesteve02** [comment]
> Hi cobblesteve long time no see and eagler 1.9 is released it has elytra’s too! If u can I add it that would be amazing and also add a 1.9 mobile version thx.

I can't add 1.9 as it constantly sends requests to lock the keyboard and mouse to the tab, making it unplayble. On the other hand for 1.12, where is the web client? I only see ways to build a desktop client.

- Cobblesteve

**Comment by bahabryra** [comment]
Thank you for your controbutions to this we will think about adding it but 1.9 and 1.12 don’t acctually fully work so we may not be adding it so please tell us how to fix the problems cobblesteve said above thanks

**Comment by cobblesteve01** [comment]
1.9, 1.11, 1.12, and 1.14 have been added.
